# Generated by Django 2.2.7 on 2019-11-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('script', models.FilePathField(path=None)),
                ('script_tag', models.FilePathField(path=None)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterToDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyportal.Character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ponyportal.Document')),
            ],
        ),
    ]
