# Generated by Django 2.2.7 on 2019-11-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponyportal', '0002_remove_document_script_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='script_tag',
            field=models.FilePathField(default='ok', path=None),
            preserve_default=False,
        ),
    ]
