# Generated by Django 2.2.7 on 2019-11-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponyportal', '0003_document_script_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='script',
        ),
        migrations.RemoveField(
            model_name='document',
            name='script_tag',
        ),
    ]
